=== Liam-LightChild/aurora/aurora/aether/ashdr.xsd
<schema xmlns:aether="https://www.liamcoalstudio.com/aurora/aether.xsd"
        xmlns:sh="https://www.liamcoalstudio.com/aurora/ashdr.xsd"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="https://www.liamcoalstudio.com/aurora/ashdr.xsd"
        attributeFormDefault="qualified"
        elementFormDefault="qualified"
        xsi:schemaLocation="https://www.liamcoalstudio.com/aurora/ashdr.xsd ashdr.xsd">
    <import namespace="https://www.liamcoalstudio.com/aurora/aether.xsd" schemaLocation="aether.xsd"/>

    <simpleType name="shader_input">
        <restriction base="string">
            <enumeration value="position2"/>
            <enumeration value="position3"/>
            <enumeration value="color3_rgb"/>
            <enumeration value="color4_rgba"/>
            <enumeration value="tex1"/>
            <enumeration value="tex2"/>
            <enumeration value="tex3"/>
        </restriction>
    </simpleType>

    <simpleType name="shader_input_type">
        <restriction>
            <enumeration value="Float"/>
            <enumeration value="Int"/>
        </restriction>
    </simpleType>

    <element name="shader">
        <complexType>
            <all>
                <element name="vertex">
                    <complexType mixed="true">
                        <sequence>
                            <element name="input" maxOccurs="unbounded">
                                <complexType>
                                    <attribute name="name" type="string" use="required"/>
                                    <attribute name="element_type" type="sh:shader_input_type" use="required"/>
                                    <attribute name="size" type="int" use="required"/>
                                    <attribute name="from" type="sh:shader_input" use="required"/>
                                </complexType>
                            </element>
                            <element name="uniform" maxOccurs="unbounded" minOccurs="0">
                                <complexType>
                                    <attribute name="name" type="string" use="required"/>
                                    <attribute name="from" type="string" use="required"/>
                                </complexType>
                            </element>
                            <element name="glsl" type="string"/>
                        </sequence>
                    </complexType>
                </element>

                <element name="pixel">
                    <complexType mixed="true">
                        <sequence>
                            <element name="output">
                                <complexType>
                                    <attribute name="name" type="string" use="required"/>
                                    <attribute name="to" type="int" use="required"/>
                                </complexType>
                            </element>
                            <element name="uniform" maxOccurs="unbounded" minOccurs="0">
                                <complexType>
                                    <attribute name="name" type="string" use="required"/>
                                    <attribute name="from" type="string" use="required"/>
                                </complexType>
                            </element>
                            <element name="glsl" type="string"/>
                        </sequence>
                    </complexType>
                </element>
            </all>
            <attributeGroup ref="aether:resource"/>
        </complexType>
    </element>
</schema>

=== Liam-LightChild/aurora/test/assets/test.ashdr.xml
<sh:shader xmlns:sh="https://www.liamcoalstudio.com/aurora/ashdr.xsd"
           xmlns:aether="https://www.liamcoalstudio.com/aurora/aether.xsd"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="https://www.liamcoalstudio.com/aurora/ashdr.xsd ../../aurora/aether/ashdr.xsd
                            https://www.liamcoalstudio.com/aurora/aether.xsd ../../aurora/aether/aether.xsd"
           aether:id="test:test.shader">
    <sh:vertex>
        <sh:input sh:name="v_position" sh:from="position3"/>
        <sh:input sh:name="v_color" sh:from="color3_rgb"/>

        <sh:glsl><![CDATA[
            in vec3 v_position;
            in vec3 v_color;

            out vec3 f_color;

            void main() {
                gl_Position = vec4(v_position, 1);
                f_color = v_color;
            }
            ]]></sh:glsl>
    </sh:vertex>

    <sh:pixel>
        <sh:output sh:name="out_color" sh:to="0"/>

        <sh:glsl><![CDATA[
            in vec3 f_color;

            out vec4 out_color;

            void main() {
                out_color = vec4(f_color, 1);
            }
            ]]></sh:glsl>
    </sh:pixel>
</sh:shader>

=== Liam-LightChild/aurora/aurora/shaders/test.ashdr.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--
  - This file is part of Aurora Game Engine.
  - https://github.com/liam-lightchild/aurora
  -->

<sh:shader xmlns:sh="https://www.liamcoalstudio.com/aurora/ashdr.xsd"
           xmlns:aether="https://www.liamcoalstudio.com/aurora/aether.xsd"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="https://www.liamcoalstudio.com/aurora/ashdr.xsd ../../aurora/aether/ashdr.xsd
                            https://www.liamcoalstudio.com/aurora/aether.xsd ../../aurora/aether/aether.xsd"
           aether:id="aurora:test.shader">
    <sh:vertex>
        <sh:input sh:name="v_position" sh:element_type="Float" sh:size="3" sh:from="position3"/>
        <sh:input sh:name="v_color" sh:element_type="Float" sh:size="3" sh:from="color3_rgb"/>

        <sh:uniform sh:name="t_object" sh:from="MatrixObject"/>
        <sh:uniform sh:name="t_view" sh:from="MatrixView"/>
        <sh:uniform sh:name="t_perspective" sh:from="MatrixPerspective"/>

        <sh:glsl><![CDATA[
            in vec3 v_position;
            in vec3 v_color;

            out vec3 f_color;

            uniform mat4 t_object;
            uniform mat4 t_view;
            uniform mat4 t_perspective;

            void main() {
                gl_Position = t_perspective * (t_view * (t_object * vec4(v_position, 1)));
                f_color = v_color;
            }
        ]]></sh:glsl>
    </sh:vertex>

    <sh:pixel>
        <sh:output sh:name="out_color" sh:to="0"/>

        <sh:glsl><![CDATA[
            in vec3 f_color;

            out vec4 out_color;

            void main() {
                out_color = vec4(f_color, 1);
            }
        ]]></sh:glsl>
    </sh:pixel>
</sh:shader>
